dist: xenial
language: go
go:
  - 1.12.x
  - 1.13.x
services:
  - docker
addons:
  apt:
    chrome: stable
before_install:
  - go get -d github.com/chromedp/chromedp
script:
  - go build ./...
  - cd $GOPATH/src/github.com/chromedp/chromedp
  - go test -v
  - export GO111MODULE=off
  - go test -c
  - docker run --rm --volume=$PWD:/chromedp --entrypoint=/chromedp/chromedp.test --workdir=/chromedp --env=PATH=/headless-shell chromedp/headless-shell:latest -test.v
